image: node:20

options:
  max-time: 15 # mins

definitions:
  services:
    docker:
      memory: 2048

  steps:
    - step: &sonar
        name: Sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:2.0.0

    - step: &lint
        name: Lint
        caches:
          - node
        script:
          - npm ci
          - npm run lint

    - step: &build
        name: Build
        caches:
          - node
        script:
          - npm ci
          - npm run build

    - step: &test
        name: Run tests
        caches:
          - node
        script:
          - npm ci
          - npm run test

    - step: &deploy
        name: Deploy
        image: google/cloud-sdk:latest
        services:
         - docker
        script:
          - export PATH=/usr/bin:$PATH
          - echo ${GCP_BITBUCKET_PIPELINE_SA} | base64 --decode --ignore-garbage > client-secret.json
          - gcloud auth activate-service-account --key-file client-secret.json && rm client-secret.json
          - gcloud auth configure-docker
          - docker build -t eu.gcr.io/usmedia-containers/giz-costing-tool-api:${BITBUCKET_COMMIT} --file ./config/Dockerfile .
          - docker push eu.gcr.io/usmedia-containers/giz-costing-tool-api:${BITBUCKET_COMMIT}
          - docker tag eu.gcr.io/usmedia-containers/giz-costing-tool-api:${BITBUCKET_COMMIT} eu.gcr.io/usmedia-containers/giz-costing-tool-api:${BITBUCKET_DEPLOYMENT_ENVIRONMENT}
          - docker push eu.gcr.io/usmedia-containers/giz-costing-tool-api:${BITBUCKET_DEPLOYMENT_ENVIRONMENT}
          - gcloud config set project ${GOOGLE_PROJECT_ID}
          - gcloud config set run/region europe-west4
          - apt-get update && apt-get install gettext-base
          - >
            envsubst < config/cloudrun-${BITBUCKET_DEPLOYMENT_ENVIRONMENT}.yml > config/cloudrun-${BITBUCKET_DEPLOYMENT_ENVIRONMENT}.tmp.yml
            && mv config/cloudrun-${BITBUCKET_DEPLOYMENT_ENVIRONMENT}.tmp.yml config/cloudrun-${BITBUCKET_DEPLOYMENT_ENVIRONMENT}.yml
          - gcloud run services replace config/cloudrun-${BITBUCKET_DEPLOYMENT_ENVIRONMENT}.yml

pipelines:
  pull-requests:
    '**':
      - parallel:
          steps:
            - step: *lint
            - step: *build
            # - step: *test
            - step: *sonar

  branches:
    develop:
      - step: *build
      - step:
          name: Deploy to staging
          deployment: staging
          <<: *deploy

    # master:
    #   - step:
    #       name: Deploy to production
    #       deployment: production
    #       trigger: manual
    #       <<: *deploy

