image: node:22

options:
  max-time: 15 # mins
  docker: true

definitions:
  services:
    docker:
      memory: 2048 # mb

  caches:
    npm: ${HOME}/.npm

  steps:
    - step: &sonar
        name: Sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:2.0.0

    - step: &lint
        name: Lint
        caches:
          - node
        script:
          - npm ci --prefer-offline
          - npm run lint

    - step: &build
        name: Build
        caches:
          - npm
        script:
          - npm ci --prefer-offline
          - npm run build
        artifacts:
          - dist/**

    - step: &deploy-container
        name: Deploy Container
        image: google/cloud-sdk:latest
        services:
          - docker
        script:
          - export PATH=/usr/bin:$PATH
          - export DOCKER_CONTAINER=eu.gcr.io/usmedia-containers/giz-costing-tool-api
          - echo ${GCP_BITBUCKET_PIPELINE_SA} | base64 --decode --ignore-garbage > client-secret.json
          - gcloud auth activate-service-account --key-file client-secret.json && rm client-secret.json
          - gcloud auth configure-docker
          - docker build -t ${DOCKER_CONTAINER}:${BITBUCKET_COMMIT} --file ./config/Dockerfile .
          - docker push ${DOCKER_CONTAINER}:${BITBUCKET_COMMIT}
          - docker tag ${DOCKER_CONTAINER}:${BITBUCKET_COMMIT} ${DOCKER_CONTAINER}:${BITBUCKET_BRANCH}
          - docker push ${DOCKER_CONTAINER}:${BITBUCKET_BRANCH}
          - echo "Container - ${DOCKER_CONTAINER}:${BITBUCKET_COMMIT}"

    - step: &deploy-infra
        name: Deploy Infra
        image: pulumi/pulumi-nodejs:latest
        script:
          - cd infra/
          - export DOCKER_CONTAINER=eu.gcr.io/usmedia-containers/giz-costing-tool-api
          - echo ${GCP_BITBUCKET_PIPELINE_SA} | base64 --decode --ignore-garbage > client-secret.json
          - export GOOGLE_CREDENTIALS=`pwd`/client-secret.json
          - npm ci
          - pulumi stack select -s ${PULUMI_STACK}
          - pulumi config set cloudrun:container ${DOCKER_CONTAINER}:${BITBUCKET_COMMIT}
          - pulumi up --yes --refresh
          - rm client-secret.json

pipelines:
  pull-requests:
    '**':
      - parallel:
          steps:
            - step: *lint
            - step: *sonar

  branches:
    develop:
      - step: *build
      - step:
          <<: *deploy-container
      - step:
          name: Deploy to staging
          deployment: staging
          <<: *deploy-infra
      - step: *sonar

    master:
     - step: *build
     - step:
         <<: *deploy-container
     - step:
         <<: *deploy-infra
         deployment: production
     - step:
         name: Sync GitHub Mirror
         image: alpine/git:latest
         clone:
           enabled: false
         script:
           - git clone --bare git@bitbucket.org:usmedia/giz-costing-tool-api.git
           - cd giz-costing-tool-api.git
           - git push --mirror git@github.com:developer-usmedia/giz-costing-tool-api.git
