@host=localhost
@port=3000
@endpoint=auth

### Register
POST http://{{host}}:{{port}}/api/{{endpoint}}/register
Content-Type: application/json

{
    "email": "debug@usmedia.nl",
    "password": "HASHME"
}

### Login
POST http://{{host}}:{{port}}/api/{{endpoint}}/login
Content-Type: application/json

{
    "email": "debug@usmedia.nl",
    "password": "HASHME",
    "emailVerificationCode": "HV4KNV"
}

### Refresh JWT
POST http://{{host}}:{{port}}/api/{{endpoint}}/refresh
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "refreshToken": ""
}

### Get user from session
GET http://{{host}}:{{port}}/api/{{endpoint}}/session
Authorization: Bearer {{token}}

### Logout
POST http://{{host}}:{{port}}/api/{{endpoint}}/logout
Authorization: Bearer {{token}}

### Protected route
GET http://{{host}}:{{port}}/api/users
Authorization: Bearer {{token}}

### Start forgot-password flow
POST http://{{host}}:{{port}}/api/{{endpoint}}/forgot-password
Content-Type: application/json

{
    "email": "debug@usmedia.nl"
}

### Verify email code
POST http://{{host}}:{{port}}/api/{{endpoint}}/verify-code
Content-Type: application/json

{
    "email": "debug@usmedia.nl",
    "code": "6QGW3Q"
}

### Reset password using resetToken
POST http://{{host}}:{{port}}/api/{{endpoint}}/reset-password
Content-Type: application/json

{
    "email": "debug@usmedia.nl",
    "resetToken": "6QGW3Q",
    "newPassword": "CHANGEME"
}

### Register a new 2 factor authenticator
POST http://{{host}}:{{port}}/api/{{endpoint}}/2fa/enable
Authorization: Bearer {{token}}

@2faToken=035863
### Verify a 2fa code from authenticator
POST http://{{host}}:{{port}}/api/{{endpoint}}/2fa/verify/{{2faToken}}
Authorization: Bearer {{token}}

### Send email verification code
POST http://{{host}}:{{port}}/api/{{endpoint}}/verify-email
Content-Type: application/json

{
    "email": "debug@usmedia.nl"
}
