@host=localhost
@port=3000
@endpoint=entries
@entryId=297eaab9-dd81-481c-a3a5-d63596ccd663

### Get all
GET http://{{host}}:{{port}}/api/{{endpoint}}
Authorization: Bearer {{token}}

### Get latest 3
GET http://{{host}}:{{port}}/api/{{endpoint}}?size=3&sort=_createdAt,ASC
Authorization: Bearer {{token}}

### Get with filter
GET http://{{host}}:{{port}}/api/{{endpoint}}?year=2032
Authorization: Bearer {{token}}

### Create
POST http://{{host}}:{{port}}/api/{{endpoint}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "facilityName": "My facility",
    "country": "Nederland",
    "year": 2031
}

### Patch
PATCH http://{{host}}:{{port}}/api/{{endpoint}}/{{entryId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "year": 2041,
    "administrativeCosts": 200,
    "defaultEmployerTax": 3,
    "defaultEmployeeTax": 5,
    "facility": {
        "name": "My Spinach Facility",
        "countryCode": "UK",
        "currencyCode": "GBP",
        "product": "Spinach",
        "unitOfProduction": "Box",
        "annualProduction": 200000,
        "buyerName": "Lidl",
        "buyerProportion": 50
    },
    "benchmark": {
        "region": "São Paulo",
        "locality": "Rural",
        "localValue": 462
    }
}

### Get
GET http://{{host}}:{{port}}/api/{{endpoint}}/{{entryId}}
Authorization: Bearer {{token}}

### Delete 
DELETE http://{{host}}:{{port}}/api/{{endpoint}}/{{entryId}}
Authorization: Bearer {{token}}

### Get workers
GET http://{{host}}:{{port}}/api/{{endpoint}}/{{entryId}}/workers
Authorization: Bearer {{token}}

### Set a scenario
POST http://{{host}}:{{port}}/api/{{endpoint}}/{{entryId}}/scenario
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "type": "TYPE_ABSOLUTE_INCREASE",
    "specifications": {
        "employeeTax": 4,
        "employerTax": 1,
        "absoluteIncrease": 500
    }
}


### Update scenario
PATCH http://{{host}}:{{port}}/api/{{endpoint}}/{{entryId}}/scenario
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "specifications": {
        "employeeTax": 3,
        "employerTax": 1,
        "absoluteIncrease": 300
    }
}


### Delete a scenario
DELETE http://{{host}}:{{port}}/api/{{endpoint}}/{{entryId}}/scenario
Authorization: Bearer {{token}}