@host=localhost
@port=3000
@endpoint=users
@userId=b587063f-7676-4419-aec5-37626ae41856

### Get all users
GET http://{{host}}:{{port}}/api/{{endpoint}}

### Get all users from page 2
GET http://{{host}}:{{port}}/api/{{endpoint}}?size=2&index=3

### Get user by id
GET http://{{host}}:{{port}}/api/{{endpoint}}/{{userId}}

### Send email verification code
POST http://{{host}}:{{port}}/api/{{endpoint}}/send-email-verification

### Verify email verification code
@emailToken=67NHHN
POST http://{{host}}:{{port}}/api/{{endpoint}}/verify-email/{{emailToken}}