@host=localhost
@port=3000
@endpoint=users
@userId=f4629b0d-9c29-475e-bda0-98db8508c239

### Get all
GET http://{{host}}:{{port}}/api/{{endpoint}}

### Get all page 2
GET http://{{host}}:{{port}}/api/{{endpoint}}?size=2&index=3

### Get by id
GET http://{{host}}:{{port}}/api/{{endpoint}}/{{userId}}

### Update by id
PATCH http://{{host}}:{{port}}/api/{{endpoint}}/{{userId}}
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Patched"
}

### Delete
DELETE http://{{host}}:{{port}}/api/{{endpoint}}/{{userId}}

### Send email verification code
POST http://{{host}}:{{port}}/api/{{endpoint}}/verify-email

### Verify email verification code
@emailToken=L5MFXS
POST http://{{host}}:{{port}}/api/{{endpoint}}/verify-email/{{emailToken}}