@host=localhost
@port=3000
@endpoint=auth

### Register
POST http://{{host}}:{{port}}/api/{{endpoint}}/register
Content-Type: application/json

{
    "email": "debug@usmedia.nl",
    "password": "HASHME"
}

### Login
POST http://{{host}}:{{port}}/api/{{endpoint}}/login
Content-Type: application/json

{
    "email": "debug@usmedia.nl",
    "password": "HASHME",
    "emailVerificationCode": "ZRR9QP"
}

### Get user from session
GET http://{{host}}:{{port}}/api/{{endpoint}}/session

### Logout
POST http://{{host}}:{{port}}/api/{{endpoint}}/logout

### Protected route
GET http://{{host}}:{{port}}/api/users

### Start forgot-password flow
POST http://{{host}}:{{port}}/api/{{endpoint}}/forgot-password
Content-Type: application/json

{
    "email": "debug@usmedia.nl"
}

### Reset password using resetToken
POST http://{{host}}:{{port}}/api/{{endpoint}}/reset-password
Content-Type: application/json

{
    "email": "debug@usmedia.nl",
    "resetToken": "K5LHC",
    "newPassword": "CHANGEME"
}

### Register a new 2 factor authenticator
POST http://{{host}}:{{port}}/api/{{endpoint}}/2fa/enable

@2faToken=035863
### Verify a 2fa code from authenticator
POST http://{{host}}:{{port}}/api/{{endpoint}}/2fa/verify/{{2faToken}}

### Send email verification code
POST http://{{host}}:{{port}}/api/{{endpoint}}/verify-email
Content-Type: application/json

{
    "userId": "6f1bbfe8-254b-4126-bc7e-9fd9c50ac688"
}
