@host=localhost
@port=3000
@endpoint=simulations
@simulationId=641f4bc6-9392-44a1-b3eb-141e284a1c42

### Get all
GET http://{{host}}:{{port}}/api/{{endpoint}}

### Create
POST http://{{host}}:{{port}}/api/{{endpoint}}
Content-Type: application/json

{
    "name": "My simuluation",
    "year": 2024
}

### Get
GET http://{{host}}:{{port}}/api/{{endpoint}}/{{simulationId}}

### Delete 
DELETE http://{{host}}:{{port}}/api/{{endpoint}}/{{simulationId}}

### Get workers
GET http://{{host}}:{{port}}/api/{{endpoint}}/{{simulationId}}/workers
