@host=localhost
@port=3000
@endpoint=simulations
@simulationId=
@bearer=

### Get all simulations
GET http://{{host}}:{{port}}/api/{{endpoint}}
Authorization: Bearer {{bearer}}

### Create simulation
POST http://{{host}}:{{port}}/api/{{endpoint}}
Authorization: Bearer {{bearer}}
Content-Type: application/json

{
    "name": "My simuluation",
    "year": 2024
}


### Get a simulation
GET http://{{host}}:{{port}}/api/{{endpoint}}/{{simulationId}}
Authorization: Bearer {{bearer}}

### Get workers from simulation
GET http://{{host}}:{{port}}/api/{{endpoint}}/{{simulationId}}/workers
Authorization: Bearer {{bearer}}
