@host=localhost
@port=3000
@endpoint=simulations
@simulationId=641f4bc6-9392-44a1-b3eb-141e284a1c42

### Get all
GET http://{{host}}:{{port}}/api/{{endpoint}}

### Get latest 3
GET http://{{host}}:{{port}}/api/{{endpoint}}?size=3&sort=updatedAt,ASC

### Get with filter
GET http://{{host}}:{{port}}/api/{{endpoint}}?year=2032

### Create
POST http://{{host}}:{{port}}/api/{{endpoint}}
Content-Type: application/json

{
    "facilityName": "My facility",
    "countryCode": "FRA",
    "year": 2031
}

### Patch
PATCH http://{{host}}:{{port}}/api/{{endpoint}}/{{simulationId}}
Content-Type: application/json

{
    "year": 2041,
    "administrativeCosts": 200,
    "defaultEmployerTax": 3,
    "defaultEmployeeTax": 5,
    "facility": {
        "name": "My Spinach Facility",
        "countryCode": "UK",
        "currencyCode": "GBP",
        "product": "Spinach",
        "unitOfProduction": "Box",
        "annualProduction": 200000,
        "buyerName": "Lidl",
        "buyerProportion": 50
    },
    "benchmark": {
        "region": "São Paulo",
        "locality": "Rural",
        "localValue": 462
    }
}

### Get
GET http://{{host}}:{{port}}/api/{{endpoint}}/{{simulationId}}

### Delete 
DELETE http://{{host}}:{{port}}/api/{{endpoint}}/{{simulationId}}

### Get workers
GET http://{{host}}:{{port}}/api/{{endpoint}}/{{simulationId}}/workers
