apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: giz-costing-tool-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/cloudsql-instances: true-elevator-417011:europe-west4:giz-costing-tool-staging-postgresql
        run.googleapis.com/vpc-access-connector: projects/true-elevator-417011/locations/europe-west4/connectors/giz-costing-tool-api-vpc
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'false'
    spec:
      serviceAccountName: svc-giz-costing-tool-staging@true-elevator-417011.iam.gserviceaccount.com
      containers:
        - image: eu.gcr.io/usmedia-containers/giz-costing-tool-api:${BITBUCKET_COMMIT}
          ports:
            - name: http1
              containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          startupProbe:
            httpGet:
              path: '/health/readiness'
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: ENV
              value: 'staging'
            - name: LOG_LEVEL
              value: 'debug'
            - name: API_URL
              value: 'https://giz-costing-tool-api-6qii37ligq-ez.a.run.app'
            - name: API_PORT
              value: 3000
            - name: API_CORS_ORIGIN
              value: '*'
            - name: DB_NAME
              value: giz-costing-tool-staging
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: DB_PASSWORD
            - name: DB_HOST
              value: '10.79.32.3' # Private IP because of Google VPC
            - name: DB_PORT
              value: '5432'
            - name: JWT_EXPIRES_IN
              value: '1h'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: JWT_SECRET
            - name: BREVO_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: BREVO_API_KEY
            - name: EMAIL_FROM_ADDRESS
              value: info@usmedia.nl
            - name: EMAIL_FROM_NAME
              value: GIZ
