version: '3.8'
name: giz-costing-tool

services:
  cloudbeaver:
    container_name: giz-beaver
    image: dbeaver/cloudbeaver:23.2
    ports:
      - 3001:8978
    environment:
      CB_ADMIN_NAME: ${CB_ADMIN_NAME}
      CB_ADMIN_PASSWORD: ${CB_ADMIN_PASSWORD}
