version: '3.8'

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:23.2
    container_name: giz-beaver
    ports:
       - "3001:8978"
    environment:
      CB_ADMIN_NAME: ${CB_ADMIN_NAME}
      CB_ADMIN_PASSWORD: ${CB_ADMIN_PASSWORD}
