version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: giz-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${MIKRO_ORM_PASSWORD}
      POSTGRES_USER: ${MIKRO_ORM_USER}
      POSTGRES_DB: ${MIKRO_ORM_DB_NAME}

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"